name: rule_engine
description: A rule engine for Dart and Flutter.
version: 0.0.2
author: Pieter Delobelle<pieter.delobelle@gmail.com>
homepage: https://github.com/iPieter/rule_engine_dart

dev_dependencies:
  test: ">=0.19.0 <3.0.0"

environment:
  sdk: ">=1.19.0 <3.0.0"
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
